### ISSUE TITLE
官方 TWRP 已支持 Android 12，开发者有意向继续在官方基础上开发吗？

### ISSUE THREAD

**Issue by wanderzzzzz** [sekaiacg/android_device_xiaomi_umi_TWRP#10]
发布页面：[TWRP 3.7.0 发布](https://twrp.me/site/update/2022/10/10/3.7.0-released.html)

如果没有计划继续的话，请问现在可以直接使用官方版吗？主要疑惑是关于 AVB 的描述：

> This device uses Android Verified Boot (AVB)
> This means that installing TWRP or swiping to allow system modifications will prevent you from being able to boot. To bypass AVB's boot prevention, you will have to disable it or install a custom ROM that ships with disabled AVB.
>To disable AVB via fastboot, grab the vbmeta image from the ROM you are on, and flash it with the following command:
>`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`

**Comment by sekaiacg** [comment]
可以使用官方版，你可以自定义一些配置和更改，我并没有在小米(高通)设备上遇无法启动twrp的问题，有可能它没有针对boot和recovery，你可以参考https://github.com/sekaiacg/twrp_recovery/commit/4cbc461fff3c1608a1a2403e626cc715427548da

**Comment by wanderzzzzz** [comment]
感谢解答，目前使用官方 TWRP 3.7.0 和小米10 MIUI 13.0.7 ，可以直接使用。
