### ISSUE TITLE
https://akr-developers.com/ is down

### ISSUE THREAD

**Issue by jason-eu** [sekaiacg/android_device_xiaomi_umi_TWRP#11]
Happy New Year!

I'm a long time user of your TWRP builds for lmi (POCO F2 Pro/Redmi K30 Pro).

I see that https://akr-developers.com/ has been down for some time and I was wondering if you have a new/alternative place where you post your latest builds.

Anyway, take care, hope to hear from you soon.

**Comment by sekaiacg** [comment]
> Happy New Year!
> 
> I'm a long time user of your TWRP builds for lmi (POCO F2 Pro/Redmi K30 Pro).
> 
> I see that https://akr-developers.com/ has been down for some time and I was wondering if you have a new/alternative place where you post your latest builds.
> 
> Anyway, take care, hope to hear from you soon.


I am very sorry to reply you now, akrdl has been closed and no longer provides services, may use google dirver

**Comment by sekaiacg** [comment]
**download link:** [google drive](https://drive.google.com/drive/folders/14Y0CG8yudmrxAETnQNKULi43gAb5hdz-?usp=share_link)
