### ISSUE TITLE
Zeus recovery A12

### ISSUE THREAD

**Issue by wolfhound234** [sekaiacg/android_device_xiaomi_umi_TWRP#6]
Good afternoon, tell me if there is an opportunity to build recovery for Xiaomi 12 Pro (Zeus). I'm ready to be a tester if necessary

**Comment by sekaiacg** [comment]
ZEUS needs the twrp_12 branch to compile and I have no plans to support Xiaomi sm8450 devices.

**Comment by wolfhound234** [comment]
Perhaps it is worth motivating you somehow? Name the price if you are interested in this offer. In principle, Recovery support is not needed, only one working version is needed.

**Comment by sekaiacg** [comment]
The ZEUS maintainer will appear when twrp12 is perfected, I may not maintain it anymore.
