### ISSUE TITLE
alioth twrp can't boot into skkk twrp

### ISSUE THREAD

**Issue by cyberboh** [sekaiacg/android_device_xiaomi_umi_TWRP#7]
Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it?
Twrp version 3.6.2

**Comment by sekaiacg** [comment]
> Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it? Twrp version 3.6.2

Some people reported that PE can start.

Try to boot to twrp with`fastboot boot rec.img`

**Comment by cyberboh** [comment]
> > Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it? Twrp version 3.6.2
> 
> Some people reported that PE can start.
> 
> Try to boot to twrp with`fastboot boot rec.img`

Probably PE does not use Lineage ROM Tree. Or it has modified ROM Tree

`fastboot boot rec.img` booted to system instead of TWRP. 
Also, tested installed via ramdisk, then after it booted to SKKK splash screen , then for few seconds it boot to system, not to TWRP

**Comment by sekaiacg** [comment]
> > > Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it? Twrp version 3.6.2
> > 
> > 
> > Some people reported that PE can start.
> > Try to boot to twrp with`fastboot boot rec.img`
> 
> Probably PE does not use Lineage ROM Tree. Or it has modified ROM Tree
> 
> `fastboot boot rec.img` booted to system instead of TWRP. Also, tested installed via ramdisk, then after it booted to SKKK splash screen , then for few seconds it boot to system, not to TWRP

I've had a similar problem: booting the system when flashing a twrp that doesn't match the device.
Please confirm that the download is alioth!

**Comment by cyberboh** [comment]
> > > > Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it? Twrp version 3.6.2
> > > 
> > > 
> > > Some people reported that PE can start.
> > > Try to boot to twrp with`fastboot boot rec.img`
> > 
> > 
> > Probably PE does not use Lineage ROM Tree. Or it has modified ROM Tree
> > `fastboot boot rec.img` booted to system instead of TWRP. Also, tested installed via ramdisk, then after it booted to SKKK splash screen , then for few seconds it boot to system, not to TWRP
> 
> I've had a similar problem: booting the system when flashing a twrp that doesn't match the device. Please confirm that the download is alioth!

Yea, i've downloaded this twrp:
`https://dl.akr-developers.com/?file=skkk/TWRP/A12/v3.6.2_A12/3.6.2_12-RedmiK40_v3.6.2_A12-alioth-skkk_442bc266.img`

and when `fastboot boot rec.img` it boot to system instead of twrp
Tested on pixelplusUi rom and AOSPA rom

**Comment by sekaiacg** [comment]
> > > > > Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it? Twrp version 3.6.2
> > > > 
> > > > 
> > > > Some people reported that PE can start.
> > > > Try to boot to twrp with`fastboot boot rec.img`
> > > 
> > > 
> > > Probably PE does not use Lineage ROM Tree. Or it has modified ROM Tree
> > > `fastboot boot rec.img` booted to system instead of TWRP. Also, tested installed via ramdisk, then after it booted to SKKK splash screen , then for few seconds it boot to system, not to TWRP
> > 
> > 
> > I've had a similar problem: booting the system when flashing a twrp that doesn't match the device. Please confirm that the download is alioth!
> 
> Yea, i've downloaded this twrp: `https://dl.akr-developers.com/?file=skkk/TWRP/A12/v3.6.2_A12/3.6.2_12-RedmiK40_v3.6.2_A12-alioth-skkk_442bc266.img`
> 
> and when `fastboot boot rec.img` it boot to system instead of twrp Tested on pixelplusUi rom and AOSPA rom


I didn't find the problem, very strange.

**Comment by sekaiacg** [comment]
> > > > > Mostly caused by verified_boot state on lineage 19.0 tree. Any chance to bypass it? Twrp version 3.6.2
> > > > 
> > > > 
> > > > Some people reported that PE can start.
> > > > Try to boot to twrp with`fastboot boot rec.img`
> > > 
> > > 
> > > Probably PE does not use Lineage ROM Tree. Or it has modified ROM Tree
> > > `fastboot boot rec.img` booted to system instead of TWRP. Also, tested installed via ramdisk, then after it booted to SKKK splash screen , then for few seconds it boot to system, not to TWRP
> > 
> > 
> > I've had a similar problem: booting the system when flashing a twrp that doesn't match the device. Please confirm that the download is alioth!
> 
> Yea, i've downloaded this twrp: `https://dl.akr-developers.com/?file=skkk/TWRP/A12/v3.6.2_A12/3.6.2_12-RedmiK40_v3.6.2_A12-alioth-skkk_442bc266.img`
> 
> and when `fastboot boot rec.img` it boot to system instead of twrp Tested on pixelplusUi rom and AOSPA rom


you can try this:
[android_device_xiaomi_umi_TWRP](https://github.com/sekaiacg/device_xiaomi_alioth-TWRP)

**Comment by cyberboh** [comment]
> I didn't find the problem, very strange.

I also don't know. I want take logs, but how to take logs while phone booting?

**Comment by cyberboh** [comment]
> you can try this: [android_device_xiaomi_alioth_TWRP](https://github.com/sekaiacg/device_xiaomi_alioth-TWRP)

Ok, Can you add recovery ramdisk file to add prebuilt?

**Comment by sekaiacg** [comment]
> > I didn't find the problem, very strange.
> 
> I also don't know. I want take logs, but how to take logs while phone booting?

ramdisk uses binary files from miui, compatibility with your ROM may not be guaranteed, you can try to modify dt to compile twrp

**Comment by cyberboh** [comment]
> > > I didn't find the problem, very strange.
> > 
> > 
> > I also don't know. I want take logs, but how to take logs while phone booting?
> 
> ramdisk uses binary files from miui, compatibility with your ROM may not be guaranteed, you can try to modify dt to compile twrp

OK.
This commits fixed `fastboot boot` https://github.com/VoidUI-Devices/device_xiaomi_sm8250-common/commit/173b1ae44791b114e34de9290b9acba23b4a4462
Seems that from LineageOS 19.1 Official DT, it move recovery inside vendor_boot , that make TWRP can't boot properly.
