### ISSUE TITLE
Apollo twrp isn't showing storage files at any case

### ISSUE THREAD

**Issue by ahmedtohamy1** [sekaiacg/android_device_xiaomi_umi_TWRP#8]
With password or without password latest version or any previous versions aren't showing anything at all and not even asking for entering password 
Using aosp android 12.1 roms

**Comment by ahmedtohamy1** [comment]
[logcat.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8937428/logcat.txt)

Here's logcat from recovery might be helpful

**Comment by sekaiacg** [comment]
> [logcat.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8937428/logcat.txt)
> 
> Here's logcat from recovery might be helpful

```
06-19 08:12:16.427   573   573 I recovery: Upgrading key: /metadata/vold/metadata_encryption/key/keymaster_key_blob
06-19 08:12:16.429   564   583 E SELinux : avc:  denied  { convert_storage_key_to_ephemeral } for  scontext=u:r:recovery:s0 tcontext=u:object_r:vold_key:s0 tclass=keystore2_key permissive=1
06-19 08:12:16.429   594   594 E KeyMasterHalDevice: legacy_export_key
06-19 08:12:16.429   594   594 E KeyMasterHalDevice: ret: 0
06-19 08:12:16.429   594   594 E KeyMasterHalDevice: resp->status: -33
06-19 08:12:16.429   564   583 E keystore2: convertStorageKeyToEphemeral export_key failed, code -33
06-19 08:12:16.429   564   583 E keystore2: keystore2::error: In convert_storage_key_to_ephemeral: Failed to retrieve ephemeral key.
06-19 08:12:16.429   564   583 E keystore2:
06-19 08:12:16.429   564   583 E keystore2: Caused by:
06-19 08:12:16.429   564   583 E keystore2:     Error::Km(ErrorCode(-33))
06-19 08:12:16.429   573   573 E recovery: keystore2 Keystore exportKey returned service specific error: -33
06-19 08:12:16.429   573   573 E recovery: Failed to get ephemeral wrapped key
06-19 08:12:17.429   573   573 E Cryptfs : cryptfs_get_password_type not valid for file encryption
```
**KM_ERROR_INVALID_KEY_BLOB=-33**
The prompt key is invalid, but I don't know what AOSP does.

**Comment by ahmedtohamy1** [comment]
> > [logcat.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8937428/logcat.txt)
> > Here's logcat from recovery might be helpful
> 
> ```
> 06-19 08:12:16.427   573   573 I recovery: Upgrading key: /metadata/vold/metadata_encryption/key/keymaster_key_blob
> 06-19 08:12:16.429   564   583 E SELinux : avc:  denied  { convert_storage_key_to_ephemeral } for  scontext=u:r:recovery:s0 tcontext=u:object_r:vold_key:s0 tclass=keystore2_key permissive=1
> 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: legacy_export_key
> 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: ret: 0
> 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: resp->status: -33
> 06-19 08:12:16.429   564   583 E keystore2: convertStorageKeyToEphemeral export_key failed, code -33
> 06-19 08:12:16.429   564   583 E keystore2: keystore2::error: In convert_storage_key_to_ephemeral: Failed to retrieve ephemeral key.
> 06-19 08:12:16.429   564   583 E keystore2:
> 06-19 08:12:16.429   564   583 E keystore2: Caused by:
> 06-19 08:12:16.429   564   583 E keystore2:     Error::Km(ErrorCode(-33))
> 06-19 08:12:16.429   573   573 E recovery: keystore2 Keystore exportKey returned service specific error: -33
> 06-19 08:12:16.429   573   573 E recovery: Failed to get ephemeral wrapped key
> 06-19 08:12:17.429   573   573 E Cryptfs : cryptfs_get_password_type not valid for file encryption
> ```
> 
> **KM_ERROR_INVALID_KEY_BLOB=-33** The prompt key is invalid, but I don't know what AOSP does.

Do u have suggestions to be done?
Those are used trees from which above logs are taken
 https://github.com/VoidUI-Devices/device_xiaomi_sm8250-common
https://github.com/VoidUI-Devices/device_xiaomi_apollon

**Comment by ahmedtohamy1** [comment]
> > [logcat.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8937428/logcat.txt)
> > Here's logcat from recovery might be helpful
> 
> ```
> 06-19 08:12:16.427   573   573 I recovery: Upgrading key: /metadata/vold/metadata_encryption/key/keymaster_key_blob
> 06-19 08:12:16.429   564   583 E SELinux : avc:  denied  { convert_storage_key_to_ephemeral } for  scontext=u:r:recovery:s0 tcontext=u:object_r:vold_key:s0 tclass=keystore2_key permissive=1
> 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: legacy_export_key
> 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: ret: 0
> 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: resp->status: -33
> 06-19 08:12:16.429   564   583 E keystore2: convertStorageKeyToEphemeral export_key failed, code -33
> 06-19 08:12:16.429   564   583 E keystore2: keystore2::error: In convert_storage_key_to_ephemeral: Failed to retrieve ephemeral key.
> 06-19 08:12:16.429   564   583 E keystore2:
> 06-19 08:12:16.429   564   583 E keystore2: Caused by:
> 06-19 08:12:16.429   564   583 E keystore2:     Error::Km(ErrorCode(-33))
> 06-19 08:12:16.429   573   573 E recovery: keystore2 Keystore exportKey returned service specific error: -33
> 06-19 08:12:16.429   573   573 E recovery: Failed to get ephemeral wrapped key
> 06-19 08:12:17.429   573   573 E Cryptfs : cryptfs_get_password_type not valid for file encryption
> ```
> 
> **KM_ERROR_INVALID_KEY_BLOB=-33** The prompt key is invalid, but I don't know what AOSP does.

Also may u pick this? Seems to be the fix for our issue
https://github.com/z3c-pie/twrp_device_sony_z3c/commit/b4eec78a25719930593f1acf0af08cad09f04d76

**Comment by sekaiacg** [comment]
> > > [logcat.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8937428/logcat.txt)
> > > Here's logcat from recovery might be helpful
> > 
> > 
> > ```
> > 06-19 08:12:16.427   573   573 I recovery: Upgrading key: /metadata/vold/metadata_encryption/key/keymaster_key_blob
> > 06-19 08:12:16.429   564   583 E SELinux : avc:  denied  { convert_storage_key_to_ephemeral } for  scontext=u:r:recovery:s0 tcontext=u:object_r:vold_key:s0 tclass=keystore2_key permissive=1
> > 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: legacy_export_key
> > 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: ret: 0
> > 06-19 08:12:16.429   594   594 E KeyMasterHalDevice: resp->status: -33
> > 06-19 08:12:16.429   564   583 E keystore2: convertStorageKeyToEphemeral export_key failed, code -33
> > 06-19 08:12:16.429   564   583 E keystore2: keystore2::error: In convert_storage_key_to_ephemeral: Failed to retrieve ephemeral key.
> > 06-19 08:12:16.429   564   583 E keystore2:
> > 06-19 08:12:16.429   564   583 E keystore2: Caused by:
> > 06-19 08:12:16.429   564   583 E keystore2:     Error::Km(ErrorCode(-33))
> > 06-19 08:12:16.429   573   573 E recovery: keystore2 Keystore exportKey returned service specific error: -33
> > 06-19 08:12:16.429   573   573 E recovery: Failed to get ephemeral wrapped key
> > 06-19 08:12:17.429   573   573 E Cryptfs : cryptfs_get_password_type not valid for file encryption
> > ``` 
> >   
> > **KM_ERROR_INVALID_KEY_BLOB=-33** The prompt key is invalid, but I don't know what AOSP does.
> 
> Also may u pick this? Seems to be the fix for our issue [z3c-pie/twrp_device_sony_z3c@b4eec78](https://github.com/z3c-pie/twrp_device_sony_z3c/commit/b4eec78a25719930593f1acf0af08cad09f04d76)

This patch might work.
I will upload a version for testing later, you can wait: https://dl.akr-developers.com/?dir=skkk/TWRP/A12_TEST/v3.6.3_A12
AKR is failure！
google: https://drive.google.com/drive/folders/14Y0CG8yudmrxAETnQNKULi43gAb5hdz-?usp=sharing

**Comment by ahmedtohamy1** [comment]
nope still same here is logs

[skkkTEST1.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8945406/skkkTEST1.txt)

**Comment by sekaiacg** [comment]
> nope still same here is logs
> 
> [skkkTEST1.txt](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8945406/skkkTEST1.txt)

Find the code by searching:
[km_compat.cpp](https://cs.android.com/android/platform/superproject/+/master:system/security/keystore2/src/km_compat/km_compat.cpp;bpv=1;bpt=1;l=702?q=km_compat.cpp&gsn=convertStorageKeyToEphemeral&gs=kythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Dc%252B%252B%3Fpath%3Dsystem%2Fsecurity%2Fkeystore2%2Fsrc%2Fkm_compat%2Fkm_compat.cpp%239psP3BsyLgSPGqtxvWNntR1PhwuM7F8nUtpXx98TJx4&gs=kythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Dc%252B%252B%3Fpath%3Dsystem%2Fsecurity%2Fkeystore2%2Fsrc%2Fkm_compat%2Fkm_compat.h%236h55_AjTud1A5ouYJIgvXLOo5mu2taOLmFx9SFO4xbg)
```
ScopedAStatus
KeyMintDevice::convertStorageKeyToEphemeral(const std::vector<uint8_t>& prefixedStorageKeyBlob,
                                            std::vector<uint8_t>* ephemeralKeyBlob) {
    KMV1::ErrorCode km_error;

    /*
     * Wrapped storage keys cannot be emulated (and they don't need to, because if a platform
     * supports wrapped storage keys, then the legacy backend will support it too. So error out
     * if the wrapped storage key given is a soft keymint key.
     */
    if (prefixedKeyBlobIsSoftKeyMint(prefixedStorageKeyBlob)) {
        return convertErrorCode(KMV1::ErrorCode::UNIMPLEMENTED);
    }

    const std::vector<uint8_t>& storageKeyBlob =
        prefixedKeyBlobRemovePrefix(prefixedStorageKeyBlob);

    auto hidlCb = [&](V4_0_ErrorCode ret, const hidl_vec<uint8_t>& exportedKeyBlob) {
        km_error = convert(ret);
        if (km_error != KMV1::ErrorCode::OK) return;
        /*
         * This must return the blob without the prefix since it will be used directly
         * as a storage encryption key. But this is alright, since this wrapped ephemeral
         * key shouldn't/won't ever be used with keymint.
         */
        *ephemeralKeyBlob = exportedKeyBlob;
    };

    auto ret = mDevice->exportKey(V4_0_KeyFormat::RAW, storageKeyBlob, {}, {}, hidlCb);
    if (!ret.isOk()) {
        LOG(ERROR) << __func__ << " export_key failed: " << ret.description();
        return convertErrorCode(KMV1::ErrorCode::UNKNOWN_ERROR);
    }
    if (km_error != KMV1::ErrorCode::OK)
        LOG(ERROR) << __func__ << " export_key failed, code " << int32_t(km_error);

    return convertErrorCode(km_error);
}
```
I can't go any further to find the problem...

**Comment by sekaiacg** [comment]
I don't find legacy_export_key on my device, it should not be called.
Please check if your ROM is out of date.
