### ISSUE TITLE
 Xiaomi 11t pro A12 TWRP

### ISSUE THREAD

**Issue by iman8852** [sekaiacg/android_device_xiaomi_umi_TWRP#9]
Hi bro will u make recovery that can support a12 encryption on Xiaomi 11t pro vili?
We've already have a TWRP for a11 but touch didn't responsible and storage didn't dycript 
Will u fix these issues as u did before for many devices 
Also I can be your tester if u need anyone 
Many of users  need TWRP for a12 and they'll be thankful

**Comment by sekaiacg** [comment]
> Hi bro will u make recovery that can support a12 encryption on Xiaomi 11t pro vili? We've already have a TWRP for a11 but touch didn't responsible and storage didn't dycript Will u fix these issues as u did before for many devices Also I can be your tester if u need anyone Many of users need TWRP for a12 and they'll be thankful

I will try

**Comment by sekaiacg** [comment]
> Hi bro will u make recovery that can support a12 encryption on Xiaomi 11t pro vili? We've already have a TWRP for a11 but touch didn't responsible and storage didn't dycript Will u fix these issues as u did before for many devices Also I can be your tester if u need anyone Many of users need TWRP for a12 and they'll be thankful

google:

**Comment by sekaiacg** [comment]
> Hi bro will u make recovery that can support a12 encryption on Xiaomi 11t pro vili? We've already have a TWRP for a11 but touch didn't responsible and storage didn't dycript Will u fix these issues as u did before for many devices Also I can be your tester if u need anyone Many of users need TWRP for a12 and they'll be thankful

google: https://drive.google.com/drive/folders/1uMeHr5kvFUGuKSPjeE6rkDHG5n4J58yH?usp=sharing
boot:
`fastboot boot rec.img`
hope to start....
If it cannot be decrypted, try changing the password type.

**Comment by iman8852** [comment]
Tnx bro I'll try when I come back home

**Comment by iman8852** [comment]
Bro I tested that and everything worked fine
Tnxx
Also can u share your PayPal to anybody can send  u a coffee? 
Just vibration is so annoying can u turn if off by default?

**Comment by iman8852** [comment]
Just vibration is so annoying can u turn if off by default?

**Comment by sekaiacg** [comment]
> Bro I tested that and everything worked fine Tnxx Also can u share your PayPal to anybody can send u a coffee? Just vibration is so annoying can u turn if off by default?

Vibration is the only button feedback, it is enabled by default and will not be disabled.

**Comment by sekaiacg** [comment]
> Bro I tested that and everything worked fine Tnxx Also can u share your PayPal to anybody can send u a coffee? Just vibration is so annoying can u turn if off by default?

Vibration won't stop?

**Comment by sekaiacg** [comment]
> Bro I tested that and everything worked fine Tnxx Also can u share your PayPal to anybody can send u a coffee? Just vibration is so annoying can u turn if off by default?

Try to v3.7t2

**Comment by iman8852** [comment]
If we turned it off all vibrate options and reboot recovery it won't vibrate anymore but if i enable any of the options it will play continuing vibrate

**Comment by iman8852** [comment]
> > Bro I tested that and everything worked fine Tnxx Also can u share your PayPal to anybody can send u a coffee? Just vibration is so annoying can u turn if off by default?
> 
> Try to v3.7t2

Ok let me test

**Comment by sekaiacg** [comment]
> If we turned it off all vibrate options and reboot recovery it won't vibrate anymore but if i enable any of the options it will play continuing vibrate

I didn't understand your previous statement about the vibration, and after that someone reported that it couldn't be stopped.  t2 should fix this.

**Comment by iman8852** [comment]
I mean it was continuing vibrate if we didn't turn off all vibrating options such as keyboard or button one from TWRP setting
Yes it didn't stop in pervious build 
Hmm I'll test in some hours later when I come back home 
Tnx for your work

**Comment by iman8852** [comment]
It's fixed tnx a lot 
can u add system partition in advanced wipe cause Some useres need it to install gsi

**Comment by sekaiacg** [comment]
> It's fixed tnx a lot can u add system partition in advanced wipe cause Some useres need it to install gsi


In my understanding dynamic partitions do not need to be wiped.
It should be managed by the installer (update_engine).
If it is system vendor, these partitions will be overwritten during installation, depending on your ROM package

**Comment by iman8852** [comment]
Ok tnx bro

**Comment by iman8852** [comment]
![Uploading IMG_20220627_204340_923.jpg…]()
Anyone else having this problem? 
Maybe this can be fwded to developer?
Miui13, Android 12, Xiaomi.eu
Workaround: rm /data/extm -Rf
Before taking backup.
This report of a user

**Comment by sekaiacg** [comment]
Need to exclude /data/extm on miui

**Comment by x3mdsl** [comment]
Backup of Data fail even with data/extm removed. 
**Later Edit:** After removing /data/extm/ AND /data/fonts/files/ - backup completed just fine.

![Screenshot_2022-06-27-23-53-38](https://user-images.githubusercontent.com/103105975/176034138-a3a5fad1-e46f-41af-add8-2106b48e2b7f.png)

**Comment by iman8852** [comment]
Recovery log:
 https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8995668/recovery.log
Do u have any telegram group to give feedback there,?

**Comment by iman8852** [comment]
[recovery.log](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8995668/recovery.log)

**Comment by x3mdsl** [comment]
here is my log file: 

[recovery.log](https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8995729/recovery.log)

log file ending with: 

I:addFile '/data/fonts' including root: 1
  ==> set selinux context: u:object_r:system_data_file:s0
failed to lookup fscrypt tar policy for '/data/fonts' - '8c623ea9000000000000000000000000'
I:addFile '/data/fonts/files' including root: 1
  ==> set selinux context: u:object_r:font_data_file:s0
failed to lookup fscrypt tar policy for '/data/fonts/files' - '8c623ea9000000000000000000000000'
I:addFile '/data/fonts/files/~~z51G0AI2rksTZcElsh13mQ==' including root: 1
  ==> set selinux context: u:object_r:font_data_file:s0
failed to lookup fscrypt tar policy for '/data/fonts/files/~~z51G0AI2rksTZcElsh13mQ==' - '8c623ea9000000000000000000000000'
I:addFile '/data/fonts/files/~~z51G0AI2rksTZcElsh13mQ==/NotoColorEmoji.ttf' including root: 1
  ==> set selinux context: u:object_r:font_data_file:s0
I:Error adding file '/data/fonts/files/~~z51G0AI2rksTZcElsh13mQ==/NotoColorEmoji.ttf' to '/data/media/0/TWRP/BACKUPS/e9bb7be8/2022-06-27--23-52-22/data.f2fs.win010'
Error creating backup.
I:ERROR tarList for thread ID 0
Error creating backup.
I:InfoManager saving '/data/media/0/TWRP/BACKUPS/e9bb7be8/2022-06-27--23-52-22/data.info'
createTarFork() process ended with ERROR: 255
Backup Failed. Cleaning Backup Folder.

**Comment by x3mdsl** [comment]
After removing /data/extm AND /data/fonts/files/ - backup completed just fine. 
The /data/fonts/files/ dir have just a file called NotoColorEmoji.ttf (some theme font file).  
Maybe its a good idea of excluding /data/fonts/files/ as well.  

Oder than this, is a awesome & long awaited recovery for 11TPro. 
Thanks @sekaiacg for this!

**Comment by sekaiacg** [comment]
> After removing /data/extm AND /data/fonts/files/ - backup completed just fine. The /data/fonts/files/ dir have just a file called NotoColorEmoji.ttf (some theme font file). Maybe its a good idea of excluding /data/fonts/files/ as well.
> 
> Oder than this, is a awesome & long awaited recovery for 11TPro. Thanks @sekaiacg for this!

try t3 later

**Comment by sekaiacg** [comment]
> Recovery log: https://github.com/sekaiacg/android_device_xiaomi_umi_TWRP/files/8995668/recovery.log Do u have any telegram group to give feedback there,?

I don't have a group.
The status bar has a lot of free space below the front camera? I adjusted the position.
Try t3 later.

**Comment by x3mdsl** [comment]
Is there a download link for t3?

**Comment by sekaiacg** [comment]
> Is there a download link for t3?

https://drive.google.com/drive/folders/1uMeHr5kvFUGuKSPjeE6rkDHG5n4J58yH

**Comment by iman8852** [comment]
Hi bro why does it show super instead of system it is impossible to flash gsi with that can u fix this too? 
![IMG_20220628_115854_239](https://user-images.githubusercontent.com/70715575/176120405-3f88af28-0a93-4cbc-bea4-aaf9f18eaaf2.jpg)
Also screenshots can't be taken from gsi
Please fix them in t4 build in twrp

**Comment by sekaiacg** [comment]
> Hi bro why does it show super instead of system it is impossible to flash gsi with that can u fix this too? ![IMG_20220628_115854_239](https://user-images.githubusercontent.com/70715575/176120405-3f88af28-0a93-4cbc-bea4-aaf9f18eaaf2.jpg) Also screenshots can't be taken from gsi Please fix them in t4 build in twrp

You're using T3? 

Dynamic Partitions: https://source.android.com/devices/tech/ota/dynamic_partitions

**Comment by iman8852** [comment]
It's for t2 
It's problem of some users not mine
Totally I use miui based Coustom roms
So idk about gsi
do u know how can them flash gsi without making problem with dynamic partition in twrp?

**Comment by sekaiacg** [comment]
> It's for t2 It's problem of some users not mine Totally I use miui based Coustom roms So idk about gsi do u know how can them flash gsi without making problem with dynamic partition in twrp?

In t3, I modified the status bar with the proactive distance

1.reboot-fastboot, enter fastbootd mode.
In fbd, use `fastboot flash system|vendor|system_ext|odm|product xxx.img`

2.Flasing super.img to super partition.

**Comment by iman8852** [comment]
Yeah I see it's much better than before
Ok tnx for your guid

**Comment by sekaiacg** [comment]
> Yeah I see it's much better than before Ok tnx for your guid

twrp device tree:
https://github.com/sekaiacg/android_device_xiaomi_vili_TWRP

**Comment by iman8852** [comment]
Tnx
